blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/takacube/ToDoOrganize/issues/new?template=custom.md&projects=takacube%2FToDo%2F1&labels=ToDo
